### ISSUE TITLE
Não entendi muito bem porque tua rota pra fazer POST em anúncio usa /login 

### ISSUE THREAD

**Issue by thalytafabrine** [pedrohcm/pdw-backend#3]
Acredito que tenha sido um engano na hora de fazer as rotas 😁 
https://github.com/pedrohcm/pdw-backend/blob/ef753fe14eda42f94c80d153d9f2308c8c34d81c/src/anuncios/anuncio.route.js#L11

**Comment by pedrohcm** [comment]
Foi erro de digitação mesmo rs
